# Generated by Django 3.2.7 on 2021-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='blogs/')),
            ],
        ),
    ]
